[package]
name = "mock-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fakeit = "1.1.1"
log = "0.4.17"
rand = "0.8.5"
